//
//  RocketsWorker.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 8/18/21.
//  Copyright (c) 2021 ___SpaceX___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import PromiseKit

class RocketsWorker
{
    var rocketsWebService: RocketsWebSeriveProtocol
    init(rocketsWebService: RocketsWebSeriveProtocol) {
        self.rocketsWebService = rocketsWebService
    }
    
    func fetchRockets(request: Rockets.SpaceX.Request) -> Promise<[Rocket]> {
        return self.rocketsWebService.fetchRockets(request: request)
    }
}
