//
//  RocketsInteractor.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 8/18/21.
//  Copyright (c) 2021 ___SpaceX___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketsBusinessLogic
{
    func fetchRockets(request: Rockets.SpaceX.Request)
    func sendRocketsList(request: Rockets.SendRocketDetail.Request)
}

protocol RocketsDataStore
{
    var rocketDetail: Rocket { get set }
}

class RocketsInteractor: RocketsBusinessLogic, RocketsDataStore
{
    var presenter: RocketsPresentationLogic?
    var worker: RocketsWorker?
    var rocketDetail = Rocket()
    // MARK: - FETCH ROCKETS -
    
    func fetchRockets(request: Rockets.SpaceX.Request)
    {
        worker = RocketsWorker(rocketsWebService: RocketsWebService())
        var response : Rockets.SpaceX.Response!
        worker?.fetchRockets(request: request).done({ (rockets) in
            response = Rockets.SpaceX.Response(success: true, rockets: rockets)
        }).catch({ (error) in
            response = Rockets.SpaceX.Response(success: false, rockets: nil)
        }).finally {
            self.presenter?.presentFetchedRockets(response: response)
        }
    }
    
    func sendRocketsList(request: Rockets.SendRocketDetail.Request)
    {
        self.rocketDetail = request.rocket
        let response = Rockets.SendRocketDetail.Response()
        presenter?.presentSendRocketDetail(response: response)
    }
}
