//
//  RocketsPresenter.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 8/18/21.
//  Copyright (c) 2021 ___SpaceX___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketsPresentationLogic
{
    func presentFetchedRockets(response: Rockets.SpaceX.Response)
    func presentSendRocketDetail(response: Rockets.SendRocketDetail.Response)
}

class RocketsPresenter: RocketsPresentationLogic
{
    weak var viewController: RocketsDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedRockets(response: Rockets.SpaceX.Response)
    {
        let viewModel = Rockets.SpaceX.ViewModel(rockets: response.rockets)
        viewController?.displayRockets(viewModel: viewModel)
    }
    
    func presentSendRocketDetail(response: Rockets.SendRocketDetail.Response)
    {
        let viewModel = Rockets.SendRocketDetail.ViewModel()
        viewController?.displaySendRocketDetail(viewModel: viewModel)
    }
}
