//
//  RocketsModels.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 8/18/21.
//  Copyright (c) 2021 ___SpaceX___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum Rockets
{
    // MARK: Use cases
    
    enum SpaceX
    {
        struct Request
        {
            var test : Bool = false
            var sslPinningEnabled = false
        }
        struct Response
        {
            var success : Bool?
            var rockets: [Rocket]?
        }
        struct ViewModel
        {
            var success : Bool?
            var rockets: [Rocket]?
        }
    }
    enum SendRocketDetail
    {
        struct Request
        {
            var rocket: Rocket
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
            
        }
    }
}

