//
//  RocketDetailModels.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 3/23/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RocketDetail
{
  // MARK: Use cases
  
  enum GetRocketDetail
  {
    struct Request
    {
    }
    struct Response
    {
        var rocket: Rocket?
    }
    struct ViewModel
    {
        var rocket: Rocket?
    }
  }
}
