//
//  RocketDetailPresenter.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 3/23/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketDetailPresentationLogic
{
    func presentRocketDetail(response: RocketDetail.GetRocketDetail.Response)
}

class RocketDetailPresenter: RocketDetailPresentationLogic
{
    weak var viewController: RocketDetailDisplayLogic?
    func presentRocketDetail(response: RocketDetail.GetRocketDetail.Response)
    {
        let viewModel = RocketDetail.GetRocketDetail.ViewModel(rocket: response.rocket)
        viewController?.displayRocketDetail(viewModel: viewModel)
    }
}
