//
//  RocketDetailInteractor.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 3/23/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketDetailBusinessLogic
{
  func getRocketDetail(request: RocketDetail.GetRocketDetail.Request)
}

protocol RocketDetailDataStore
{
  var rocketDetail: Rocket { get set }
}

class RocketDetailInteractor: RocketDetailBusinessLogic, RocketDetailDataStore
{
  var presenter: RocketDetailPresentationLogic?
  var worker: RocketDetailWorker?
  var rocketDetail = Rocket()
  
  // MARK: Do something
  
    func getRocketDetail(request: RocketDetail.GetRocketDetail.Request)
  {
      let response = RocketDetail.GetRocketDetail.Response(rocket: rocketDetail)
      presenter?.presentRocketDetail(response: response)
  }
}
