//
//  RocketsPresenterTests.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 7/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSpaceX
import XCTest

class RocketsPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: RocketsPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupRocketsPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupRocketsPresenter()
  {
    sut = RocketsPresenter()
  }
  
  // MARK: Test doubles
  
  class RocketsDisplayLogicSpy: RocketsDisplayLogic
    {
      var displayGetRockets = false
      var displaySendRockets = false
      
      
      func displayRockets(viewModel: Rockets.SpaceX.ViewModel) {
          self.displayGetRockets = true
      }
      
      func displaySendRocketDetail(viewModel: Rockets.SendRocketDetail.ViewModel) {
          self.displaySendRockets = true
      }
     
  }
  
  // MARK: Tests
  
  func testPresentRockets()
  {
    // Given
    let spy = RocketsDisplayLogicSpy()
    sut.viewController = spy
    let response = Rockets.SpaceX.Response()
    
    // When
    sut.presentFetchedRockets(response: response)
    
    // Then
    XCTAssertTrue(spy.displayGetRockets, "presentFetchedRockets(response:) should ask the view controller to display the result")
  }
    
    
    func testPresentSendRockets()
    {
        // Given
        let spy = RocketsDisplayLogicSpy()
        sut.viewController = spy
        let response = Rockets.SendRocketDetail.Response()
        
        // When
        sut.presentSendRocketDetail(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySendRockets, "presentSendRockets(response:) should ask the view controller to display the result")
    }
}
