//
//  RocketsInteractorTests.swift
//  CleanSpaceX
//
//  Created by Ahmed Iqbal on 7/2/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSpaceX
import XCTest

class RocketsInteractorTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: RocketsInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupRocketsInteractor()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupRocketsInteractor()
    {
        sut = RocketsInteractor()
    }
    
    // MARK: Test doubles
    
    class RocketsPresentationLogicSpy: RocketsPresentationLogic
    {
        var presentFetchedRocketsCalled = false
        var presentSendRocketDetailCalled = false
        
        func presentFetchedRockets(response: Rockets.SpaceX.Response) {
            presentFetchedRocketsCalled = true
        }
        
        func presentSendRocketDetail(response: Rockets.SendRocketDetail.Response) {
            presentSendRocketDetailCalled = true
        }
        
    }
    
    // MARK: Tests
    
    func testGetRockets()
    {
        // Given
        let spy = RocketsPresentationLogicSpy()
        sut.presenter = spy
        let request = Rockets.SpaceX.Request(test: true, sslPinningEnabled: false)
        
        // When
        sut.fetchRockets(request: request)
        
        let expectation = XCTestExpectation(description: "rockets")
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0, execute: {
            
            // Then
            XCTAssertTrue(spy.presentFetchedRocketsCalled, "getRocketsLookups(request:) should ask the presenter to format the result")
            expectation.fulfill()
        })
        
        wait(for: [expectation], timeout: 5.0)
    }
}
